# Generated by Django 4.2.7 on 2023-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_medicaldoctor_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='aorta',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Left Side'), (2, 'Right Side'), (3, 'Dilatation'), (4, 'Dissection')], null=True),
        ),
    ]
