# Generated by Django 4.2.7 on 2023-12-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_study_aorta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
    ]
