# Generated by Django 4.2.7 on 2023-12-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_case_related_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='related_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_study_set', to='core.study'),
        ),
    ]
