# Generated by Django 4.2.7 on 2023-12-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_case_related_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study', to='core.case'),
        ),
    ]
