# Generated by Django 4.2.7 on 2023-12-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_study_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='annulus',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='apex',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='apical_anterior',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='apical_inferior',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='apical_lateral',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='apical_septal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='avg_mean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='avg_peak',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='basal_anterior',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='basal_anterolateral',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='basal_anteroseptal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='basal_inferior',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='basal_inferolateral',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='basal_inferoseptal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_diastolic_diameter',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_diastolic_diameter_bsa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_diastolic_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_diastolic_volume_bsa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_ef',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_mass',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_mass_2d_method',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_mass_bsa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_mass_bsa_2d_method',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_mass_bsa_linear_method',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_mass_linear_method',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_systolic_diameter',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_systolic_diameter_bsa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_systolic_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='lv_systolic_volume_bsa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mid_anterior',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mid_anterolateral',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mid_anteroseptal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mid_inferior',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mid_inferolateral',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mid_inferoseptal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mvg_mean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='mvg_peak',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='posterior_wall_thickness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='proximal_ascending_aorta',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='rv_basal_diameter',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='rv_mid_diameter',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='septal_wall_thickness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='sinotublar_junction',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='sinuses_of_valsalva',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True),
        ),
    ]
