# Generated by Django 4.2.7 on 2023-12-01 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to=settings.AUTH_USER_MODEL),
        ),
    ]
