# Generated by Django 4.2.7 on 2023-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
