# Generated by Django 4.2.7 on 2023-12-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_supervisor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='name',
            new_name='abbreviated_name',
        ),
    ]
